main: main.o Angestellter.o Manager.o
	g++ main.cpp -o main Angestellter.o Manager.o

Angestellter: Angestellter.o Angestellter.h
	g++ Angestellter.cpp -c

Manager: Manager.o Manager.h
	g++ Manager.cpp -c
