main: main.c ascii.o multTable.o dual.o toUpperCase.o
	gcc main.c -o main ascii.o multTable.o dual.o toUpperCase.o

ascii.o: ascii.c
	gcc ascii.c -c

multTable.o: multTable.c
	gcc multTable.c -c

dual.o: dual.c
	gcc dual.c -c

toUpperCase: toUpperCase.c
	gcc toUpperCase.c -c