main: main.cpp Character.h Character.o Inventory.h Inventory.o
	g++ main.cpp -o main Character.o Inventory.o

Character: Character.h Character.cpp
	g++ Character.cpp -c

Inventory: Inventory.h Inventory.cpp
	g++ Inventory.cpp -c